name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Chrome for Selenium
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser

    - name: Backend - Install & Test
      run: |
        cd server
        npm ci
        npm test
        npm run test:api

    - name: Frontend - Install & Test
      run: |
        cd client
        npm ci
        npm test
        npm run test:ui

    - name: Run Selenium Tests
      run: |
        cd client
        npm run test:selenium

    - name: Build Frontend
      run: |
        cd client
        npm run build

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Upload Test Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: |
          server/coverage/
          client/coverage/