name: CI Pipeline - Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # Clone repo

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'  # Your Node version

    - name: Backend Build & Test
      run: |
        cd server
        npm ci
        npm test

    - name: Frontend Build & Test
      run: |
        cd client
        npm ci
        npm test

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Upload Test Reports (if fail)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: |
          server/coverage/
          client/coverage/